# Generated by Django 4.1.2 on 2022-10-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='member', max_length=60),
        ),
    ]
